### ISSUE TITLE
Sending commands to cc2541

### ISSUE THREAD

**Issue by R-Francois** [ameltech/sme-cc2541-library#3]
Hello,

I am using the cc2541 library and examples are working just fine. Thanks to the application 
B-BLE (BLE4.0 Scan), I am able to communicate between the Smartphone App and the SmartEverything USB console.

I would like to know if it possible to send commands to the cc2541 to get some information about BlueTooth and configure it.

My goal is to get RSSI of the Smartphone knowing its address. Maybe I could send a command to enter in Inquiry mode, check if the Smartphone is available and get its RSSI. Is this achievable? 

Regards

**Comment by searobin** [comment]
Unforunaley the BLE Fw just work as a bridge. just as passthrough serial connection
