### ISSUE TITLE
How to pair two Arduinos with CC2541 BLE chips? Is that even possible?

### ISSUE THREAD

**Issue by rkkoszewski** [ameltech/sme-cc2541-library#4]
Hi,
I have two Arduino Smart Everything, both with the same CC2541 BLE chip, and I'm trying to make them communicate to each other. But I somehow cannot find how to pair two devices automatically nor even how to change the device name to something different than 'FOX-BRDG'.

Is it even posible to do that with this devices? If yes, where can I find information on how to do so?

Thanks and Greetings.

**Comment by searobin** [comment]
the name can't be changed. It is in the ble fw. The communication should be possible. Please refer to the readme in the Github. Repository of the library. It is a serial protocol based on TI fw.

**Comment by rkkoszewski** [comment]
Hi,
Thanks @searobin. I'm reading trough the documentation.

One thing, in cc2541.cpp (https://github.com/ameltech/sme-cc2541-library/blob/master/src/ble/cc2541.cpp)

Where does the BLE class come from? There are several calls like BLE.available(), BLE.read(), BLE.print() and BLE.write() but I cannot find the source class anywhere.. 

Does anybody knows where it is? Thanks.

**Comment by searobin** [comment]
Hi Robert.

BLE identifies the serial line connected to the CC2541 (it is the UART class).

**Comment by searobin** [comment]
It is defined in the Board library:

https://github.com/ameltech/sme-arduino-core/blob/master/hardware/AMEL/samd/variants/AMEL_SmartEverything/variant.cpp
